Stat svc
MariaNzrv/java-explore-with-me pull request #1
Opened 2024-08-17 18:32 UTC by MariaNzrv

2024-08-18 10:55 UTC, tomattman requested changes
Привет, перебор с запросами в сервисе, все остальное рекомендуемо но опционально

2024-08-18 10:55 UTC, tomattman commented on stats/stats-dto/src/main/java/ru/practicum/HitRequest.java
> +public class HitRequest {
так как это похоже Dto рекомендую и в имя класса это добавить и поместить в пакет dto

2024-08-18 10:55 UTC, tomattman commented on stats/stats-dto/src/main/java/ru/practicum/HitRequest.java
> +public class HitRequest {
хотя пакет опционально, ведь подпроект называется stats-dto
но при разбиении на пакеты обычно базовый пакет- имеет имя проекта

2024-08-18 10:55 UTC, tomattman commented on stats/stats-server/src/main/java/ru/practicum/controller/StatsController.java
> +        LocalDateTime startDateTime = LocalDateTime.parse(URLDecoder.decode(start, StandardCharsets.UTF_8), formatter);
можно сделать декодеры которые будут автоматически применятся на контроллеры и в параметрах принимать не строку, а сразу нормальный объект LocalDateTime

2024-08-18 10:55 UTC, tomattman commented on stats/stats-server/src/main/java/ru/practicum/service/StatsService.java
> +            sql = "select distinct app_id, uri, count(id) as hits " +
составление запросов в базу данных это точно не логика сервиса
1) можно сделать отдельный репозиторий для таких специфических запросов
2) можно именованные запросы так же поместить в интерфейс

2024-08-18 18:22 UTC, MariaNzrv commented on stats/stats-dto/src/main/java/ru/practicum/HitRequest.java
> +public class HitRequest {
сделано

2024-08-18 20:26 UTC, MariaNzrv commented on stats/stats-server/src/main/java/ru/practicum/service/StatsService.java
> +            sql = "select distinct app_id, uri, count(id) as hits " +
сделано

2024-08-18 20:50 UTC, MariaNzrv commented on stats/stats-server/src/main/java/ru/practicum/controller/StatsController.java
> +        LocalDateTime startDateTime = LocalDateTime.parse(URLDecoder.decode(start, StandardCharsets.UTF_8), formatter);
сделано

2024-08-19 09:58 UTC, tomattman approved these changes
Принято

2024-08-19 17:03 UTC, merged